version: "3"

services:
  valheim-server:
    container_name: valheim-server
    hostname: valheim-server
    image: ghcr.io/kesokaj/valheim-server:v1
    volumes:
    - ./saves:/home/steam/.config/unity3d/IronGate/Valheim/
    environment:
    - TZ=Europe/Stockholm
    - SERVER_NAME=KESOKAJ Playground
    - SERVER_PASSWORD=freeplay
    - WORLD_NAME=Dedicated
    ports:
    - "2456-2457:2456-2457/udp"
    restart: unless-stopped
    stop_grace_period: 30s
